# Copyright (c) 2022-2026, The Isaac Lab Project Developers.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Constants for SimpleFlight task."""

# Physical constants
GRAVITY_MAGNITUDE = 9.81
CRAZYFLIE_MASS = 0.0321

# Control constants
CONTROL_FREQUENCY_HZ = 50
SIM_SUBSTEPS = 2
SIMULATION_DT = 1.0 / (CONTROL_FREQUENCY_HZ * SIM_SUBSTEPS)

# Crazyflie motor parameters
MAX_THRUST_RATIO = 0.9
MIN_THRUST_RATIO = 0.0
PWM_RESOLUTION = 65536
MAX_ROTATION_VELOCITY_RAD_S = 2315.0
FORCE_CONSTANT = 2.350347298350041e-08
MOMENT_CONSTANT = 7.24e-10
MOTOR_TIME_CONSTANT_S = 0.025

# PID rate controller gains (matched to firmware)
PID_RATE_KP = [250.0, 250.0, 120.0]
PID_RATE_KI = [500.0, 500.0, 16.7]
PID_RATE_KD = [2.5, 2.5, 0.0]
PID_RATE_I_LIMIT = [33.3, 33.3, 166.7]
PID_RATE_OUT_LIMIT = float(PWM_RESOLUTION - 1)

# Action scaling
TARGET_RATE_CLIP_DEG_S = 180.0
LPF_COEFFICIENT = 1.0

# Observation noise parameters
POSITION_NOISE_STD_M = 0.001
VELOCITY_NOISE_STD_M_S = 0.01
ANGULAR_VELOCITY_NOISE_STD_RAD_S = 0.01
ORIENTATION_NOISE_STD_RAD = 0.005

# Latency simulation
ENABLE_LATENCY_SIMULATION = True
LATENCY_STEPS = 1
ENABLE_RANDOM_LATENCY = True

# Episode settings
EPISODE_LENGTH_S = 20.0
MAX_TRAJECTORY_STEPS = 10
TRAJECTORY_STEP_SIZE = 5

# Reset thresholds
RESET_HEIGHT_THRESHOLD_M = 0.1
RESET_DISTANCE_THRESHOLD_M = 1.0

# Reward weights
REWARD_DISTANCE_SCALE = 5.0
REWARD_UP_WEIGHT = 1.0
REWARD_SPIN_WEIGHT = 1.0
REWARD_ACTION_SMOOTHNESS_WEIGHT_INIT = 2.0
REWARD_ACTION_SMOOTHNESS_WEIGHT_LR = 0.0005
REWARD_SMOOTHNESS_MAX = 2.0
REWARD_ACTION_NORM_WEIGHT_INIT = 0.0
REWARD_ACTION_NORM_WEIGHT_LR = 0.0001
REWARD_NORM_MAX = 0.0

# Domain randomization ranges
DR_MASS_SCALE_RANGE = (0.7, 1.3)
DR_INERTIA_SCALE_RANGE = (0.9, 1.1)
DR_DRAG_COEF_SCALE_RANGE = (0.9, 1.1)
DR_TAU_SCALE_RANGE = (0.8, 1.2)

# Wind disturbance
ENABLE_WIND = False
WIND_INTENSITY_RANGE = (0.0, 2.0)

# Environment spacing
ENV_SPACING_M = 2.5
